DROP TABLE IF EXISTS auth CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS states CASCADE;
DROP TABLE IF EXISTS resources; 
DROP TABLE IF EXISTS favorites CASCADE;
DROP TABLE IF EXISTS additional_data;

DROP TABLE IF EXISTS populations CASCADE;
DROP TABLE IF EXISTS topics CASCADE;
DROP TABLE IF EXISTS additional_data CASCADE;
DROP TABLE IF EXISTS favorites CASCADE;
DROP TABLE IF EXISTS resources; 

CREATE TABLE auth (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL
);

CREATE TABLE resources (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  resource_name TEXT NOT NULL,
  resource_url TEXT NOT NULL,
  state_abrv TEXT,
  topics_id BIGINT,
  FOREIGN KEY (state_abrv) REFERENCES states(abrv),
  FOREIGN KEY (topics_id) REFERENCES topics(id)
);

CREATE TABLE users (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  auth_email TEXT NOT NULL UNIQUE,
  username TEXT,
  avatar TEXT,
  FOREIGN KEY (auth_email) REFERENCES auth(email)
);

CREATE TABLE topics (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);


CREATE TABLE states (
  state_name TEXT NOT NULL PRIMARY KEY,
  abrv TEXT UNIQUE NOT NULL
);

CREATE TABLE resources (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  resource_name TEXT NOT NULL,
  resource_url TEXT NOT NULL,
  state_abrv TEXT,
  topics_id BIGINT,
  FOREIGN KEY (state_abrv) REFERENCES states(abrv),
  FOREIGN KEY (topics_id) REFERENCES topics(id)
);

CREATE TABLE favorites (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  image TEXT NOT NULL,
  user_id BIGINT NOT NULL REFERENCES users(id),
  topic_id BIGINT NOT NULL REFERENCES topics(id)
);

CREATE TABLE additional_data (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  data DECIMAL(8,2),
  state TEXT NOT NULL,
  FOREIGN KEY (state) REFERENCES states(abrv),
  category TEXT NOT NULL,
  topic TEXT REFERENCES topics(name)
  -- topic2 TEXT REFERENCES topics(name)
);

CREATE TABLE populations (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  state_abrv TEXT,
  total NUMERIC,
  lgbt NUMERIC,
  aa Numeric,
  latinx Numeric,
  -- api DECIMAL(8,2),
  FOREIGN KEY (state_abrv) REFERENCES states(abrv)
);

INSERT INTO auth (email, password_hash) VALUES('test@email.com', '1234');
INSERT INTO auth (email, password_hash) VALUES('testTwo@email.com', '4321');
INSERT INTO auth (email, password_hash) VALUES('testThree@email.com', '4321');
INSERT INTO users (auth_email) VALUES('test@email.com');
INSERT INTO users (auth_email) VALUES('testTwo@email.com');

INSERT INTO topics (name) VALUES 
(‘Homelessness’, null),
(‘Food’),
(‘LGBTQ’),
(‘Poverty’);

INSERT INTO states (state_name, abrv) VALUES ('alabama', 'AL'),
('alaska', 'AK'),
('arizona', 'AZ'),
('arkansas', 'AR'),
('california', 'CA'),
('colorado', 'CO'),
('connecticut', 'CT'),
('delaware', 'DE'),
('florida', 'FL'),
('georgia', 'GA'),
('hawaii', 'HI'),
('idaho', 'ID'),
('illinois', 'IL'),
('indiana', 'IN'),
('iowa', 'IA'),
('kansas', 'KS'),
('kentucky', 'KY'),
('louisiana', 'LA'),
('maine', 'ME'),
('maryland', 'MD'),
('massachusetts', 'MA'),
('michigan', 'MI'),
('minnesota', 'MN'),
('mississippi', 'MS'),
('missouri', 'MO'),
('montana', 'MT'),
('nebraska', 'NB'),
('nevada', 'NV'),
('new hampshire', 'NH'),
('new jersey', 'NJ'),
('new mexico', 'NM'),
('new york', 'NY'),
('north carolina', 'NC'),
('north dakota', 'ND'),
('ohio', 'OH'),
('oklahoma', 'OK'),
('oregon', 'OR'),
('pennsylvania', 'PA'),
('rhode island', 'RI'),
('south dakota', 'SD'),
('south carolina', 'SC'),
('tennessee', 'TN'),
('texas', 'TX'),
('utah', 'UT'),
('vermont', 'VT'),
('virginia', 'VA'),
('washington', 'WA'),
('west virginia', 'WV'),
('wisconsin', 'WI'),
('wyoming', 'WY');


-- (‘0.58’, ‘AL’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘0.34’, ‘AK’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘1.9’, ‘AZ’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘0.41’, ‘AR’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘27.89’, ‘CA’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘0.11’, ‘CO’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘0.5’, ‘CT’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘0.2’, ‘DE’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘4.75’, ‘FL’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘1.77’, ‘GA’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘1.11’, ‘HI’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘0.4’, ‘ID’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘1.8’, ‘IL’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘0.97’, ‘IN’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘0.46’, ‘IA’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘0.42’, ‘KS’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘0.69’, ‘KY’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘0.55’, ‘LA’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘0.36’, ‘ME’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘1.1’, ‘MD’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘3.1’, ‘MA’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘1.49’, ‘MI’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘1.37’, ‘MN’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘0.19’, ‘MS’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘1.13’, ‘MO’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘0.27’, ‘MT’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘0.42’, ‘NB’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘1.19’, ‘NV’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘0.29’, ‘NH’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘1.67’, ‘NJ’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘0.58’, ‘NM’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘15.76’, ‘NY’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘1.6’, ‘NC’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘0.09’, ‘ND’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘1.84’, ‘OH’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘0.68’, ‘OK’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘2.53’, ‘OR’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘2.31’, ‘PA’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘0.19’, ‘RI’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘0.18’, ‘SD’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘0.74’, ‘SC’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘1.25’, ‘TN’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘4.7’, ‘TX’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘0.54’, ‘UT’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘0.19’, ‘VT’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘1.03’, ‘VA’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘3.96’, ‘WA’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘0.23’, ‘WV’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘0.78’, ‘WI’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- (‘0.11’, ‘WY’, ‘Percentage of Total Population Experiencing Homelessness’, ‘Homelessness’, null),
-- -- (‘null’, ‘AL’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- -- (‘null’, ‘AK’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- -- (‘null’, ‘AZ’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- -- (‘null’, ‘AR’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘223700’, ‘CA’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘21500’, ‘CO’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘14500’, ‘CT’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘3200’, ‘DE’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘7800’, ‘FL’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘34300’, ‘GA’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘8600’, ‘HI’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘7900’, ‘ID’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘73800’, ‘IL’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘44200’, ‘IN’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘12900’, ‘IA’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘10900’, ‘KS’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘26500’, ‘KY’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- -- (‘null’, ‘LA’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- -- (‘null’, ‘ME’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘30900’, ‘MD’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘23300’, ‘MA’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- -- (‘null’, ‘MI’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘15300’, ‘MN’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘10600’, ‘MS’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘25600’, ‘MO’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘5600’, ‘MT’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- -- (‘null’, ‘NB’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘16100’, ‘NV’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- -- (‘null’, ‘NH’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- -- (‘null’, ‘NJ’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- -- (‘null’, ‘NM’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘105600’, ‘NY’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘45800’, ‘NC’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- -- (‘null’, ‘ND’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘46600’, ‘OH’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘26800’, ‘OK’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- -- (‘null’, ‘OR’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘46200’, ‘PA’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘6100’, ‘RI’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- -- (‘null’, ‘SD’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘17100’, ‘SC’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- -- (‘null’, ‘TN’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘133300’, ‘TX’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- -- (‘null’, ‘UT’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘3800’, ‘VT’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘25400’, ‘VA’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘39600’, ‘WA’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘5800’, ‘WV’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘18900’, ‘WI’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘2600’, ‘WY’, ‘LGBT People in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- -- (‘null’, ‘AL’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- -- (‘null’, ‘AK’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- -- (‘null’, ‘AZ’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- -- (‘null’, ‘AR’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘23’, ‘CA’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘18’, ‘CO’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘18’, ‘CT’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘15’, ‘DE’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘07’, ‘FL’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘22’, ‘GA’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘24’, ‘HI’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘28’, ‘ID’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘25’, ‘IL’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘29’, ‘IN’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘24’, ‘IA’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘24’, ‘KS’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘28’, ‘KY’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- -- (‘null’, ‘LA’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- -- (‘null’, ‘ME’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘23’, ‘MD’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘13’, ‘MA’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- -- (‘null’, ‘MI’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘16’, ‘MN’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘29’, ‘MS’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘22’, ‘MO’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘31’, ‘MT’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- -- (‘null’, ‘NB’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘23’, ‘NV’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- -- (‘null’, ‘NH’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- -- (‘null’, ‘NJ’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- -- (‘null’, ‘NM’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘2’, ‘NY’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘18’, ‘NC’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- -- (‘null’, ‘ND’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘22’, ‘OH’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘31’, ‘OK’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- -- (‘null’, ‘OR’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘18’, ‘PA’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘21’, ‘RI’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- -- (‘null’, ‘SD’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘2’, ‘SC’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- -- (‘null’, ‘TN’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘28’, ‘TX’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- -- (‘null’, ‘UT’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘18’, ‘VT’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘17’, ‘VA’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘18’, ‘WA’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘22’, ‘WV’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘16’, ‘WI’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’),
-- (‘27’, ‘WY’, ‘Percentage of LGBT Population in Poverty’, ‘LGBTQ’, ‘Poverty’);


-- INSERT INTO resources(resource_name, resource_url, state_abrv, topics_id)
-- VALUES
-- ('Free Food- by region', 'https://www.freefood.org', '', '2'),
-- (‘GLBT ADVOCACY & YOUTH SERVICES, INC. (GLBTAYS)’, ’https://www.glbtays.org/', ‘AL’, ‘3’),
-- (‘Houseless to Independence’, ’https://www.homelesstoindependence.org/alabama/alabama-emergency-services/', ‘AL’, ‘1’),
-- (‘IDENTITY, INC’, ’https://identityalaska.org/', ‘AK’, ‘1’),
-- (‘Alaska Housing Finance Corporation’, ’https://www.ahfc.us/', ‘AK’, ‘1’),
-- (‘DES Utility Assistance ’, ’https://des.az.gov/services/basic-needs/shelter-housing/utility-assistance', ‘AZ’, ‘1’),
-- (‘DES Houseless Services’, ’https://des.az.gov/services/basic-needs/shelter-housing/homeless-services', ‘AZ’, ‘1’),
-- (‘Arkansas Hunger Relief Alliance’, ’https://arhungeralliance.org/emergency-resources/', ‘AR’, ‘1’),
-- (‘Arkansas Department of Human Services: Programs’, ’https://humanservices.arkansas.gov/learn-about-programs/', ‘AR’, ‘1’),
-- (‘Project Roomkey’, ’https://www.cdss.ca.gov/inforesources/cdss-programs/housing-programs/project-roomkey', ‘CA’, ‘1’),
-- (‘CDSS Housing and Homelessness Programs’, ’https://www.cdss.ca.gov/inforesources/cdss-programs/housing-programs', ‘CA’, ‘1’),
-- (‘COVID19 Housing and Rent Help’, ’https://covid19.ca.gov/housing-and-homelessness/#People-experiencing-homelessness', ‘CA’, ‘1’),
-- (‘Colorado Coalition for the Homeless’, ’https://www.coloradocoalition.org/gethelp', ‘CO’, ‘1’),
-- (‘CT Health and Human Services’, ’https://portal.ct.gov/Services/Health-and-Human-Services', ‘CT’, ‘1’),
-- (‘Delaware Health and Social Services’, ’https://dhss.delaware.gov/dhss/', ‘DE’, ‘1’),
-- (‘Florida Coalition to End Homelessness’, ’http://fchonline.org/resources/', ‘FL’, ‘1’),
-- (‘Georgia Department of Community Affairs: Food’, ’https://www.dca.ga.gov/safe-affordable-housing/homeless-special-needs-housing/covid-19-resources/food', ‘GA’, ‘1’),
-- (‘University of Hawaii at Manoa: List of Local Organizations Addressing Homelessness’, ’https://guides.library.manoa.hawaii.edu/c.php?g=105635&p=684598', ‘HI’, ‘1’),
-- (‘Idaho Housing and Finance Association’, ’https://www.idahohousing.com/homelessness-services-programs/', ‘ID’, ‘1’),
-- (‘Jesse Tree’, ’https://www.jessetreeidaho.org/', ‘ID’, ‘1’),
-- (‘Illinois Department of Human Services: Housing, Shelter, and Homelessness Resources’, ’https://www.dhs.state.il.us/page.aspx?item=124295', ‘IL’, ‘1’),
-- (‘Coalition for Homelessness Intervention and Prevention: Handbook of Help’, ’http://handbookofhelp.org/', ‘IN’, ‘1’),
-- (‘Shelter House Iowa’, ’https://shelterhouseiowa.org/programs-and-services/', ‘IA’, ‘1’),
-- (‘Iowa Finance Authority’, ’https://www.iowafinance.com/homelessness/', ‘IA’, ‘1’),
-- (‘KUMC JayDoc Free Clinic: Community Resources’, ’https://www.kumc.edu/school-of-medicine/patient-care/student-run-clinics/jaydoc-free-clinic/resources/community-assistance-resources.html', ‘KS’, ‘1’),
-- (‘KC Footprints for Houseless Veterans’, ’https://www.kcfootprints.org/', ‘KS’, ‘1’),
-- (‘KC Footprints For Houseless Veterans’, ’https://www.kcfootprints.org/', ‘MO’, ‘1’),
-- (‘Sheffield Place’, ’https://www.sheffieldplace.org/programs', ‘MO’, ‘1’),
-- (‘HHCK: Housing Programs’, ’https://www.hhck.org/housing-programs', ‘KY’, ‘1’),
-- (‘Louisiana BOSCO: Housing and Services’, ’https://laboscoc.org/housing-and-services/', ‘LA’, ‘1’),
-- (‘Maine Housing’, ’https://www.mainehousing.org/programs-services/homeless/emergency-shelters', ‘ME’, ‘1’),
-- (‘Maryland Department of Housing and Community Development’, ’https://dhcd.maryland.gov/HomelessServices/Pages/default.aspx', ‘MD’, ‘1’),
-- (‘Massachusetts Department of Housing and Community Development’, ’https://www.mass.gov/orgs/housing-and-community-development', ‘MA’, ‘1’),
-- (‘Project Bread’, ’https://www.projectbread.org/get-help', ‘MA’, ‘1’),
-- (‘811 Project Rental Assistance Program’, ’https://www.michigan.gov/mshda/homeless/811/811-project-rental-assistance-pra-program', ‘MI’, ‘1’),
-- (‘NEMCSA Houseless and Prevention Services’, ’https://www.nemcsa.org/services/homeless-prevention-program/', ‘MI’, ‘1’),
-- (‘Disability Hub’, ’https://mn.hb101.org/i/map/homeless_map.htm', ‘MN’, ‘1’),
-- (‘Mississippi United to End Homelessness’, ’https://www.muteh.org/', ‘MS’, ‘1’),
-- (‘Missouri Department of Social Services’, ’https://dss.mo.gov/fsd/esg/', ‘MO’, ‘1’),
-- (‘St. Louis Houseless Services’, ’https://www.stlouis-mo.gov/government/departments/human-services/homeless-services/Homeless-Resources.cfm', ‘MO’, ‘1’),
-- (‘Poverello Center’, ’https://www.thepoverellocenter.org/programs-and-services/', ‘MT’, ‘1’),
-- (‘Nebraska Department of Health and Human Services: Houseless Assistance’, ’https://dhhs.ne.gov/Pages/Homeless-Assistance.aspx#', ‘NE’, ‘1’),
-- (‘Nevada Houseless Alliance’, ’https://nevadahomelessalliance.org/gethelp/', ‘NV’, ‘1’),
-- (‘NH DHHS: Shelter Services’, ’https://www.dhhs.nh.gov/dcbcs/bhhs/shelter.htm', ‘NH’, ‘1’),
-- (‘NJ Covid-19 Information Hub’, ’https://covid19.nj.gov/faqs/nj-information/assistance-and-benefits/how-do-i-apply-for-food-cash-and-health-insurance-assistance-how-are-assistance-programs-adjusting-for-covid-19', ‘NJ’, ‘1’),
-- (‘Housing New Mexico’, ’https://housingnm.org/find-housing/emergency-shelter', ‘NM’, ‘1’),
-- (‘Supportive Housing Coalition of New Mexico’, ’https://www.shcnm.org/communities/', ‘NM’, ‘1’),
-- (‘NY Coalition for the Homeless’, ’https://www.coalitionforthehomeless.org/get-help/', ‘NY’, ‘1’),
-- (‘NC Coalition to End Homelessness’, ’https://www.ncceh.org/lookingforhelp/coordinatedassessment/', ‘NC’, ‘1’),
-- (‘NC Houseless Education Program’, ’https://hepnc.uncg.edu/', ‘NC’, ‘1’),
-- (‘North Dakota Houseless Coalition’, ’https://www.ndhomelesscoalition.org/resources', ‘ND’, ‘1’),
-- (‘ND DHS: Resources for people who are Houseless or at risk of homelessness’, ’https://www.nd.gov/dhs/info/covid-19/housing-homelessness.html', ‘ND’, ‘1’),
-- (‘Coalition on Homelessness and Housing in Ohio’, ’http://cohhio.org/housing-information/', ‘OH’, ‘1’),
-- (‘Ohio Legal Help’, ’https://www.ohiolegalhelp.org/', ‘OH’, ‘1’),
-- (‘Ohio Association of Foodbanks’, ’https://ohiofoodbanks.org/foodbanks/', ‘OH’, ‘1’),
-- (‘Heartline Oaklahoma’, ’https://heartlineoklahoma.org/', ‘OK’, ‘1’),
-- (‘Housing Oregon’, ’https://housingoregon.org/resources-for-homelessness-services-covid-19-crisis/#', ‘OR’, ‘1’),
-- (‘Portland Houseless Family Solutions’, ’http://www.pdxhfs.org/housing', ‘OR’, ‘1’),
-- (‘Interactive Map of Restrooms and Hygiene Stations’, ’https://pdx.maps.arcgis.com/apps/webappviewer/index.html?id=3abca53221c64d6a9e35c5c8572a9696', ‘OR’, ‘1’),
-- (‘Pennsylvania Youth Congress’, ’https://payouthcongress.org/resources/emergency-housing/', ‘PE’, ‘1’),
-- (‘Philadelphia Office of Houseless Services’, ’http://philadelphiaofficeofhomelessservices.org/', ‘PE’, ‘1’),
-- (‘Rhode Island Community Foodbank’, ’https://rifoodbank.org/find-food/', ‘RI’, ‘1’),
-- (‘Rhode Island Coalition to End Homelessness’, ’https://www.rihomeless.org/help', ‘RI’, ‘1’),
-- (‘SCIWAY’, ’https://www.sciway.net/org/sc-homeless.html', ‘SC’, ‘1’),
-- (‘Cornerstone Rescue Mission’, ’http://www.cornerstonemission.org/', ‘SD’, ‘1’),
-- (‘HUD Help Hotlines: South Dakota’, ’https://www.hud.gov/states/south_dakota/homeless/hsghelp', ‘SD’, ‘1’),
-- (‘Tennessee Department of Mental Health and Substance Abuse Services’, ’https://www.tn.gov/behavioral-health/housing/additional-programs.html', ‘TN’, ‘1’),
-- (‘TN State Plan to End Homelessness’, ’https://www.tn.gov/content/dam/tn/mentalhealth/documents/TN_Homeless_Resources.pdf', ‘TN’, ‘1’),
-- (‘TX HHS: Programs & Services’, ’https://www.hhs.texas.gov/services/mental-health-substance-use/mental-health-crisis-services/programs-people-who-are-homeless-or-risk-becoming-homeless', ‘TX’, ‘1’),
-- (‘The Road Home’, ’https://theroadhome.org/', ‘UT’, ‘1’),
-- (‘SLCO Crisis Information & Outreach’, ’https://slco.org/homeless-services/resource-directory/crisis-information-and-outreach/', ‘UT’, ‘1’),
-- (‘VT DCF Benefit Programs’, ’https://dcf.vermont.gov/benefits', ‘VT’, ‘1’),
-- (‘Vermont Coalition to End Homelessness’, ’https://helpingtohousevt.org/', ‘VT’, ‘1’),
-- (‘HUD Houseless Services Providers: VA’, ’https://www.hud.gov/states/virginia/homeless/providers', ‘VA’, ‘1’),
-- (‘WA Department of Commerce’, ’https://www.commerce.wa.gov/serving-communities/homelessness/', ‘WA’, ‘1’),
-- (‘Pierce County: Houseless Programs’, ’https://www.piercecountywa.gov/3715/Homeless-Programs', ‘WA’, ‘1’),
-- (‘Houseless Shelters Directory’, ’https://www.homelessshelterdirectory.org/state/west_virginia', ‘WV’, ‘1’),
-- (‘WV DHHR’, ’http://www.wvdhhr.org/bph/tollfree.htm', ‘WV’, ‘1’),
-- (‘WV DHHR: Family Assistance’, ’https://dhhr.wv.gov/bcf/Services/familyassistance/Pages/default.aspx', ‘WV’, ‘1’),
-- (‘WI Department of Children & Families: Houseless Services’, ’https://dcf.wisconsin.gov/homeless', ‘WI’, ‘1’),
-- (‘WI Department of Children & Families: Resources for Runaway and Houseless Youth’, ’https://dcf.wisconsin.gov/map/rhy', ‘WI’, ‘1’),
-- (‘Wyoming 211: Community Services’, ’https://wy211.communityos.org/', ‘WY’, ‘1’);

INSERT INTO populations(state_abrv, total, lgbt, aa, latinx)
VALUES ('AL', 4903185, 117000, 1296162, 264067),
('AK', 731545, 21000, 21898, 49824),
('AZ', 7278717, 242000, 339150, 2192253),
('AR', 3017804, 76000, 453783, 256847),
('CA', 39512223, 1615000, 2237044, 15579652),
('CO', 5758736, 200000, 234828, 1263390),
('CT', 3565287, 111000, 388675, 623293),
('DE', 973764, 34000, 218899, 104290),
('FL', 217477737, 772000, 3246381, 5697240),
('GA', 10617423, 356000, 3320513, 1123457),
('HI', 1415872, 52000, 23417, 138293),
('ID', 1787065, 36000, 15726, 239407),
('IL', 12671821, 426000, 1808271, 2337410),
('IN', 6732219, 229000, 648513, 554191),
('IA', 3155070, 87000, 131972, 215986),
('KS', 2913314, 73000, 168809, 382603),
('KY', 4467673, 117000, 362417, 207854),
('LA', 4648794, 139000, 1464023, 322549),
('ME', 1344212, 53000, 25752, 26609),
('MD', 6045680, 198000, 1820427, 729746),
('MA', 6892503, 296000, 494029, 887685),
('MI', 9986857, 311000, 1376579, 564422),
('MN', 5639632, 175000, 398434, 345640),
('MS', 2976149, 79000, 1084481, 105220),
('MO', 6137428, 180000, 699840, 303068),
('MT', 1068778, 24000, 5484, 45199),
('NB', 1934408, 55000, 96535, 234715),
('NV', 3080156, 127000, 304739, 890257),
('NH', 1359711, 51000, 20127, 59454),
('NJ', 8882190, 288000, 1219770, 20002575),
('NM', 2096829, 72000, 45904, 1010811),
('NY', 19453561, 800000, 2986172, 3948032),
('NC', 10488084, 319000, 2140217, 1118596),
('ND', 762062, 16000, 30067, 33412),
('OH', 11689100, 389000, 1478781, 521308),
('OK', 3956971, 113000, 289961, 471931),
('OR', 42177737, 183000, 82655, 588757),
('PA', 12801989, 416000, 1423169, 1049615),
('RI', 1059361, 38000, 62168, 182101),
('SD', 884659, 20000, 1280531, 38741),
('SC', 5148714, 137000, 17842, 352838),
('TN', 6829174, 182000, 1092948, 479187),
('TX', 28995881, 858000, 3552997, 11441717),
('UT', 3205968, 80000, 40058, 492912),
('VT', 623989, 26000, 9034, 15504),
('VA', 8535519, 257000, 1607581, 908749),
('WA', 7614893, 300000, 307565, 1059213),
('WV', 1792147, 58000, 65813, 34827),
('WI', 5822434, 171000, 376256, 447290),
('WY', 578759, 15000, 5232, 59046);

INSERT INTO additional_data( data, state, topic) VALUES
('3351', 'AL', 'Total_Homeless_Population'),
('1949', 'AK', 'Total_Homeless_Population'),
('10979', 'AZ', 'Total_Homeless_Population'),
('2366', 'AR', 'Total_Homeless_Population'),
('161548', 'CA', 'Total_Homeless_Population'),
('9846', 'CO', 'Total_Homeless_Population'),
('2905', 'CT', 'Total_Homeless_Population'),
('1165', 'DE', 'Total_Homeless_Population'),
('27487', 'FL', 'Total_Homeless_Population'),
('10234', 'GA', 'Total_Homeless_Population'),
('6458', 'HI', 'Total_Homeless_Population'),
('2315', 'ID', 'Total_Homeless_Population'),
('10431', 'IL', 'Total_Homeless_Population'),
('5625', 'IN', 'Total_Homeless_Population'),
('2647', 'IA', 'Total_Homeless_Population'),
('2449', 'KS', 'Total_Homeless_Population'),
('4011', 'KY', 'Total_Homeless_Population'),
('3173', 'LA', 'Total_Homeless_Population'),
('2097', 'ME', 'Total_Homeless_Population'),
('6360', 'MD', 'Total_Homeless_Population'),
('17975', 'MA', 'Total_Homeless_Population'),
('8638', 'MI', 'Total_Homeless_Population'),
('7940', 'MN', 'Total_Homeless_Population'),
('1107', 'MS', 'Total_Homeless_Population'),
('6527', 'MO', 'Total_Homeless_Population'),
('1545', 'MT', 'Total_Homeless_Population'),
('2404', 'NB', 'Total_Homeless_Population'),
('6900', 'NV', 'Total_Homeless_Population'),
('1675', 'NH', 'Total_Homeless_Population'),
('9662', 'NJ', 'Total_Homeless_Population'),
('3333', 'NM', 'Total_Homeless_Population'),
('91271', 'NY', 'Total_Homeless_Population'),
('9280', 'NC', 'Total_Homeless_Population'),
('541', 'ND', 'Total_Homeless_Population'),
('10655', 'OH', 'Total_Homeless_Population'),
('3932', 'OK', 'Total_Homeless_Population'),
('14655', 'OR', 'Total_Homeless_Population'),
('13375', 'PA', 'Total_Homeless_Population'),
('1104', 'RI', 'Total_Homeless_Population'),
('1058', 'SD', 'Total_Homeless_Population'),
('4287', 'SC', 'Total_Homeless_Population'),
('7256', 'TN', 'Total_Homeless_Population'),
('27229', 'TX', 'Total_Homeless_Population'),
('3131', 'UT', 'Total_Homeless_Population'),
('1110', 'VT', 'Total_Homeless_Population'),
('5957', 'VA', 'Total_Homeless_Population'),
('22923', 'WA', 'Total_Homeless_Population'),
('1341', 'WV', 'Total_Homeless_Population'),
('4515', 'WI', 'Total_Homeless_Population'),
('612', 'WY', 'Total_Homeless_Population'),
('0.58', 'AL', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('0.34', 'AK', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('1.9', 'AZ', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('0.41', 'AR', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('27.89', 'CA', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('0.11', 'CO', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('0.5', 'CT', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('0.2', 'DE', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('4.75', 'FL', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('1.77', 'GA', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('1.11', 'HI', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('0.4', 'ID', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('1.8', 'IL', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('0.97', 'IN', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('0.46', 'IA', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('0.42', 'KS', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('0.69', 'KY', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('0.55', 'LA', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('0.36', 'ME', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('1.1', 'MD', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('3.1', 'MA', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('1.49', 'MI', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('1.37', 'MN', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('0.19', 'MS', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('1.13', 'MO', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('0.27', 'MT', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('0.42', 'NB', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('1.19', 'NV', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('0.29', 'NH', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('1.67', 'NJ', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('0.58', 'NM', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('15.76', 'NY', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('1.6', 'NC', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('0.09', 'ND', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('1.84', 'OH', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('0.68', 'OK', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('2.53', 'OR', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('2.31', 'PA', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('0.19', 'RI', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('0.18', 'SD', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('0.74', 'SC', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('1.25', 'TN', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('4.7', 'TX', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('0.54', 'UT', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('0.19', 'VT', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('1.03', 'VA', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('3.96', 'WA', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('0.23', 'WV', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('0.78', 'WI', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
('0.11', 'WY', 'Percentage_of_Total_Population_Experiencing_Homelessness'),
-- ('null', 'AL', 'LGBT_People_in_Poverty'),
-- ('null', 'AK', 'LGBT_People_in_Poverty'),
-- ('null', 'AZ', 'LGBT_People_in_Poverty'),
-- ('null', 'AR', 'LGBT_People_in_Poverty'),
('223700', 'CA', 'LGBT_People_in_Poverty'),
('21500', 'CO', 'LGBT_People_in_Poverty'),
('14500', 'CT', 'LGBT_People_in_Poverty'),
('3200', 'DE', 'LGBT_People_in_Poverty'),
('7800', 'FL', 'LGBT_People_in_Poverty'),
('34300', 'GA', 'LGBT_People_in_Poverty'),
('8600', 'HI', 'LGBT_People_in_Poverty'),
('7900', 'ID', 'LGBT_People_in_Poverty'),
('73800', 'IL', 'LGBT_People_in_Poverty'),
('44200', 'IN', 'LGBT_People_in_Poverty'),
('12900', 'IA', 'LGBT_People_in_Poverty'),
('10900', 'KS', 'LGBT_People_in_Poverty'),
('26500', 'KY', 'LGBT_People_in_Poverty'),
-- ('null', 'LA', 'LGBT_People_in_Poverty'),
-- ('null', 'ME', 'LGBT_People_in_Poverty'),
('30900', 'MD', 'LGBT_People_in_Poverty'),
('23300', 'MA', 'LGBT_People_in_Poverty'),
-- ('null', 'MI', 'LGBT_People_in_Poverty'),
('15300', 'MN', 'LGBT_People_in_Poverty'),
('10600', 'MS', 'LGBT_People_in_Poverty'),
('25600', 'MO', 'LGBT_People_in_Poverty'),
('5600', 'MT', 'LGBT_People_in_Poverty'),
-- ('null', 'NB', 'LGBT_People_in_Poverty'),
('16100', 'NV', 'LGBT_People_in_Poverty'),
-- ('null', 'NH', 'LGBT_People_in_Poverty'),
-- ('null', 'NJ', 'LGBT_People_in_Poverty'),
-- ('null', 'NM', 'LGBT_People_in_Poverty'),
('105600', 'NY', 'LGBT_People_in_Poverty'),
('45800', 'NC', 'LGBT_People_in_Poverty'),
-- ('null', 'ND', 'LGBT_People_in_Poverty'),
('46600', 'OH', 'LGBT_People_in_Poverty'),
('26800', 'OK', 'LGBT_People_in_Poverty'),
-- ('null', 'OR', 'LGBT_People_in_Poverty'),
('46200', 'PA', 'LGBT_People_in_Poverty'),
('6100', 'RI', 'LGBT_People_in_Poverty'),
-- ('null', 'SD', 'LGBT_People_in_Poverty'),
('17100', 'SC', 'LGBT_People_in_Poverty'),
-- ('null', 'TN', 'LGBT_People_in_Poverty'),
('133300', 'TX', 'LGBT_People_in_Poverty'),
-- ('null', 'UT', 'LGBT_People_in_Poverty'),
('3800', 'VT', 'LGBT_People_in_Poverty'),
('25400', 'VA', 'LGBT_People_in_Poverty'),
('39600', 'WA', 'LGBT_People_in_Poverty'),
('5800', 'WV', 'LGBT_People_in_Poverty'),
('18900', 'WI', 'LGBT_People_in_Poverty'),
('2600', 'WY', 'LGBT_People_in_Poverty'),
-- ('null', 'AL', 'Percentage_of_LGBT_Population_in_Poverty'),
-- ('null', 'AK', 'Percentage_of_LGBT_Population_in_Poverty'),
-- ('null', 'AZ', 'Percentage_of_LGBT_Population_in_Poverty'),
-- ('null', 'AR', 'Percentage_of_LGBT_Population_in_Poverty'),
('23', 'CA', 'Percentage_of_LGBT_Population_in_Poverty'),
('18', 'CO', 'Percentage_of_LGBT_Population_in_Poverty'),
('18', 'CT', 'Percentage_of_LGBT_Population_in_Poverty'),
('15', 'DE', 'Percentage_of_LGBT_Population_in_Poverty'),
('07', 'FL', 'Percentage_of_LGBT_Population_in_Poverty'),
('22', 'GA', 'Percentage_of_LGBT_Population_in_Poverty'),
('24', 'HI', 'Percentage_of_LGBT_Population_in_Poverty'),
('28', 'ID', 'Percentage_of_LGBT_Population_in_Poverty'),
('25', 'IL', 'Percentage_of_LGBT_Population_in_Poverty'),
('29', 'IN', 'Percentage_of_LGBT_Population_in_Poverty'),
('24', 'IA', 'Percentage_of_LGBT_Population_in_Poverty'),
('24', 'KS', 'Percentage_of_LGBT_Population_in_Poverty'),
('28', 'KY', 'Percentage_of_LGBT_Population_in_Poverty'),
-- ('null', 'LA', 'Percentage_of_LGBT_Population_in_Poverty'),
-- ('null', 'ME', 'Percentage_of_LGBT_Population_in_Poverty'),
('23', 'MD', 'Percentage_of_LGBT_Population_in_Poverty'),
('13', 'MA', 'Percentage_of_LGBT_Population_in_Poverty'),
-- ('null', 'MI', 'Percentage_of_LGBT_Population_in_Poverty'),
('16', 'MN', 'Percentage_of_LGBT_Population_in_Poverty'),
('29', 'MS', 'Percentage_of_LGBT_Population_in_Poverty'),
('22', 'MO', 'Percentage_of_LGBT_Population_in_Poverty'),
('31', 'MT', 'Percentage_of_LGBT_Population_in_Poverty'),
-- ('null', 'NB', 'Percentage_of_LGBT_Population_in_Poverty'),
('23', 'NV', 'Percentage_of_LGBT_Population_in_Poverty'),
-- ('null', 'NH', 'Percentage_of_LGBT_Population_in_Poverty'),
-- ('null', 'NJ', 'Percentage_of_LGBT_Population_in_Poverty'),
-- ('null', 'NM', 'Percentage_of_LGBT_Population_in_Poverty'),
('2', 'NY', 'Percentage_of_LGBT_Population_in_Poverty'),
('18', 'NC', 'Percentage_of_LGBT_Population_in_Poverty'),
-- ('null', 'ND', 'Percentage_of_LGBT_Population_in_Poverty'),
('22', 'OH', 'Percentage_of_LGBT_Population_in_Poverty'),
('31', 'OK', 'Percentage_of_LGBT_Population_in_Poverty'),
-- ('null', 'OR', 'Percentage_of_LGBT_Population_in_Poverty'),
('18', 'PA', 'Percentage_of_LGBT_Population_in_Poverty'),
('21', 'RI', 'Percentage_of_LGBT_Population_in_Poverty'),
-- ('null', 'SD', 'Percentage_of_LGBT_Population_in_Poverty'),
('2', 'SC', 'Percentage_of_LGBT_Population_in_Poverty'),
-- ('null', 'TN', 'Percentage_of_LGBT_Population_in_Poverty'),
('28', 'TX', 'Percentage_of_LGBT_Population_in_Poverty'),
-- ('null', 'UT', 'Percentage_of_LGBT_Population_in_Poverty'),
('18', 'VT', 'Percentage_of_LGBT_Population_in_Poverty'),
('17', 'VA', 'Percentage_of_LGBT_Population_in_Poverty'),
('18', 'WA', 'Percentage_of_LGBT_Population_in_Poverty'),
('22', 'WV', 'Percentage_of_LGBT_Population_in_Poverty'),
('16', 'WI', 'Percentage_of_LGBT_Population_in_Poverty'),
('27', 'WY', 'Percentage_of_LGBT_Population_in_Poverty');
